### ISSUE TITLE
New release required

### ISSUE THREAD

**Issue by drapela-connyun** [Azure/iot-edge-opc-publisher#123]
Hi,
 
We are configuring the opc-publisher exclusively via its OPC server “façade”. This means, we do not have access to the “publishednodes.json” file. We also require that the messages sent to the iot-hub contains the expanded node id (nsu+id), and not the old format. Because of that, we depend on the fix pushed with the commit (“Fix async naming, fix usage of ExpandedNodeId syntax usage, fix locking”, https://github.com/Azure/iot-edge-opc-publisher/commit/6b6af1e7fbede015a37643d9abc7903375fda8ce). Unfortunately, this and many other (important) fixes came after the last release 2.1.4. Can you please create a new release that contains fixes pushed since 2.1.4?
 
Thanks,
Diego

**Comment by jcharlytown** [comment]
Hi,

maybe I can help to clarify. First of all, we have a specific objective: We'd like the publisher to always use the ExpandedNodeId ("nsu=" syntax) when sending telemetry data to the IoT Hub, not plain NodeId ("ns=" syntax). Afaik, the publisher chooses the format with which the "MonitoredItem" has been configured in the first place: https://github.com/Azure/iot-edge-opc-publisher/blob/maintenance_2_1/src/OpcSession.cs#L172

What @diegorapela is basically saying is that we do not have access to the json file for configuring the nodes to publish, we need to do any configuration via the "PublishNode" and "UnpublishNode" OPC UA server methods. However, for version 2.1.4, "PublishNode" seems to not handle ExpandedNodeIds correctly. On input `NodeId="nsu=http://kuka.com/opcuaserver/;s=MotionDeviceSystem.MotionDevices.MotionDevice_1.Axes.Axis_1.ParameterSet.ActualPosition"` it ends up with:

```
"Result": [{
  "EndpointUrl": "opc.tcp://192.168.1.20:4840",
  "NodeId": {
    "Identifier": "s=nsu=http://kuka.com/opcuaserver/;s=MotionDeviceSystem.MotionDevices.MotionDevice_1.Axes.Axis_1.ParameterSet.ActualPosition"
  }
}]
```

On the other hand, using "latest" this issue seems to be fixed. As @diegorapela mentioned, it seems that https://github.com/Azure/iot-edge-opc-publisher/commit/6b6af1e7fbede015a37643d9abc7903375fda8ce is the commit in question. Hence our question: Would you consider this a bug fix which would be applicable for 2.1.X maintenance branch? If yes, would that then entail a 2.1.5 release?

**Comment by hansgschossmann** [comment]
You are right, this was not handled correct. I will look into this.

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by marcschier** [comment]
This should be in 2.4.x release and given that 2.x is backwards compatible we are not planning to touch 2.1.x releases, unless there is a good reason.   If latter, please re-open.
